parameters:
#    piwicms_client_newsletter.example.class: Piwicms\Client\NewsletterBundle\Example

services:
#    piwicms_client_newsletter.example:
#        class: %piwicms_client_newsletter.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
