parameters:
#    piwicms_admin_web.example.class: Piwicms\Admin\WebBundle\Example

services:
#    piwicms_admin_web.example:
#        class: %piwicms_admin_web.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
