<?php

namespace Piwicms\System\CoreBundle\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * PrivateMessageRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class PrivateMessageRepository extends EntityRepository
{
    public function findPrivateMessagesOfUser($user)
    {
        $q = $this
            ->createQueryBuilder('u')
            ->where('u.toUser = :user')
            ->setParameter('user', $user)
            ->orderBy('u.created', 'DESC')
            ->getQuery()
        ;

        $tasks = $q->getArrayResult();
        if (empty($tasks)) {
            return array();
        }

        return $tasks;
    }
}
