<?php

namespace Piwicms\System\CoreBundle\Repository;

use Doctrine\ORM\EntityRepository;
use Doctrine\ORM\NoResultException;

/**
 * SystemSettingsRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class SystemSettingsRepository extends EntityRepository
{
    public function findSystemSettingsField($module, $setting)
    {
        $q = $this
            ->createQueryBuilder('u')
            ->andWhere('u.module = :module')
            ->setParameter('module', $module)
            ->andWhere('u.setting = :setting')
            ->setParameter('setting', $setting)
            ->getQuery()
        ;

        try {
            // The Query::getSingleResult() method throws an exception
            // if there is no record matching the criteria.
            $userSetting = $q->getSingleResult();
        } catch (NoResultException $e) {
            return false;
        }

        return $userSetting;
    }

    public function findSystemSettings()
    {
        $q = $this
            ->createQueryBuilder('u')
            ->getQuery()
        ;

        $settings = $q->getResult();
        if (empty($settings)) {
            return false;
        }

        return $settings;
    }

    public function findSystemSettingsArray()
    {
        $q = $this
            ->createQueryBuilder('u')
            ->getQuery()
        ;

        $settings = $q->getArrayResult();
        if (empty($settings)) {
            return array();
        }

        $settingsArray = array();
        foreach($settings as $setting){
            $settingsArray[$setting['module']][$setting['setting']] = $setting['value'];
        }

        return $settingsArray;
    }
}
