<?php

namespace Piwicms\System\CoreBundle\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * TemplateRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class TemplateRepository extends EntityRepository
{
    public function findTemplateByName($name)
    {
        $q = $this
            ->createQueryBuilder('t')
            ->where('t.name = :name')
            ->setParameter('name', $name)
            ->setMaxResults(1)
            ->getQuery()
        ;

        return $q->getSingleResult();
    }

    public function getTemplateTimestamp($name)
    {
        $q = $this
            ->createQueryBuilder('t')
            ->select('t.modified')
            ->where('t.name = :name')
            ->setParameter('name', $name)
            ->setMaxResults(1)
            ->getQuery()
        ;

        $template = $q->getResult();

        if($template) {
            return $template->getModified()->getTimestamp();
        } else {
            return null;
        }
    }

}
