<?php

namespace Piwicms\System\CoreBundle\Repository;

use Doctrine\ORM\EntityRepository;
use Doctrine\ORM\NoResultException;

/**
 * UserSettingsRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class UserSettingsRepository extends EntityRepository
{
    public function findUserSettingsFieldOfUser($user, $setting)
    {
        $q = $this
            ->createQueryBuilder('u')
            ->where('u.user = :user')
            ->andWhere('u.setting = :setting')
            ->setParameter('user', $user)
            ->setParameter('setting', $setting)
            ->getQuery()
        ;

        try {
            // The Query::getSingleResult() method throws an exception
            // if there is no record matching the criteria.
            $userSetting = $q->getSingleResult();
        } catch (NoResultException $e) {
            return false;
        }

        return $userSetting;
    }

    public function findUserSettingsOfUser($user)
    {
        $q = $this
            ->createQueryBuilder('u')
            ->where('u.user = :user')
            ->setParameter('user', $user)
            ->getQuery()
        ;

        $userSettings = $q->getResult();
        if (empty($userSettings)) {
            return false;
        }

        return $userSettings;
    }

    public function findUserSettingsOfUserArray($user)
    {
        $q = $this
            ->createQueryBuilder('u')
            ->where('u.user = :user')
            ->setParameter('user', $user)
            ->getQuery()
        ;

        $userSettings = $q->getArrayResult();
        if (empty($userSettings)) {
            return array();
        }

        $userSettingsArray = array();
        foreach($userSettings as $userSetting){
            $userSettingsArray[$userSetting['setting']] = $userSetting['value'];
        }

        return $userSettingsArray;
    }
}
